cache: pip
language: python
python:
  - "3.6"
  - "3.7-dev"
  - "nightly"
install:
  - pip install --upgrade setuptools
  - pip install . coveralls check-manifest
script:
  - check-manifest
  - python setup.py check -m -r -s
  - python setup.py test
  - python setup.py build_sphinx -W
after_success:
  - coveralls
